version: "3.7"
networks:
  epas-internal:
    driver: bridge

services:
  epas-worker:
    build: .
    image: epas-worker
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - PUBLISH_PACKAGES =${PUBLISH_PACKAGES}
      - SQS_QUEUE_URL=${SQS_QUEUE_URL}
      - QUEUE_TYPE=SQS
      - DB_TYPE=DYNAMODB
      - NUMBER_OF_WORKERS=2
    networks:
      - epas-internal
